name: hio
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.35.1
  provider: ^6.1.5+1
  web: ^1.1.1
  ffi: ^2.2.0
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.4
  window_manager: ^0.5.1
  image: ^4.8.0
  args: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7

flutter:
  uses-material-design: true
  assets:
  - resources/data/objects/
  - resources/images/objects/
  - resources/images/textures/atlas_32.png
  - resources/images/textures/atlas_64.png
  - resources/images/textures/atlas_128.png
  - resources/data/blocks.json
  - resources/maps/